package com.lapostal.security.entities;

public enum RoleName {

	ROLE_USER,
	ROLE_PM,
	ROLE_ADMIN,	
	ROLE_STAFF_EMS,
	ROLE_STAFF_COLIS,
	ROLE_STAFF_RECOMMANDE,
	ROLE_STAFF_ORDINAIRE,
	ROLE_STAFF_ESUUQ,	
	ROLE_STAFF_LIVRAISON,
	ROLE_STAFF_RECEPTION,
	ROLE_STAFF_ENVOI,	
	ROLE_STAFF_RECETTE,	
	ROLE_STAFF_TABLEAUBORD
	
	
	
}
